# Generated by Django 5.0.7 on 2024-08-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_mgm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_add_new_project', 'can add new project')]},
        ),
    ]
